using System;
public enum SkillAttributes
{
    none = 0,
    t_attack = 1,
    t_attackRate = 2,
    t_range = 3,
    t_accuracy = 4,
    t_criticalRate = 5,
    t_criticalMultiplier = 6,
    p_splashRange = 7,
    e_defense = 8,
    e_shield = 9,
    e_speed = 10,
    skill_cooldown = 11,
    skill_duration = 12,
    skill_level = 13,
    iteration = 14,
    op_attack = 15,
    op_attackRate = 16,
    op_range = 17,
    op_accuracy = 18,
    op_criticalRate = 19,
    op_criticalMultiplier = 20,
    player_exp = 21,
    player_gold = 22,
}
public enum ProductionCategory
{
    none = 0,
    operator_same = 1,
    operator_diff = 2,
    equipment_same = 3,
    equipment_grade_diff = 4,
    equipment_diff = 5,
    material_same = 6,
    material_diff = 7,
    gold_same = 8,
    gold_diff = 9,
}
public enum QuestConditions
{
    none = 0,
    login = 1,
    stagePlay = 2,
    stageClear = 3,
    stageFail = 4,
    craft = 5,
    adWatch = 6,
    questComplete = 7,
    shopPurchase = 8,
    operatorGet = 9,
    operatorLevelup = 10,
    operatorGradeup = 11,
    skillLevelup = 12,
    equipmentGet = 13,
    enemyKill = 14,
    bossKill = 15,
    itemUse = 16,
    repeatable = 17,
    halfSquad = 18,
    fullSquad = 19,
    operatorOnDeck = 20,
    operatorLevelup50 = 21,
    operatorLevelup70 = 22,
}
